import { supabase, APP_URL, DEFAULT, RECOVERY_REDIRECT } from "../services/supabase.js";
import { CARD_CATALOG, detectCard, cardPath } from "../services/cards.js";
import { createInitialState, normalizeState, loadLocalState, saveLocalState } from "../core/state.js";
import { money, esc, monthKey, monthLabel, incomeForMonth, currentIncome, isPaidThisMonth, totals } from "../core/calculations.js";
import { accountIcon } from "../core/accounts.js";

let state=createInitialState(),session=null;
const $=id=>document.getElementById(id);
function key(){return "mi_presupuesto_v6_"+(session?.user?.id||"anon")}
function localSave(){saveLocalState(session?.user?.id,state)}
function localLoad(){const x=loadLocalState(session?.user?.id);if(x)state=x}
async function cloudLoad(){const {data,error}=await supabase.from("budget_data").select("data").eq("user_id",session.user.id).maybeSingle();if(error){console.error(error);return}if(data?.data)state=normalizeState(data.data);else await cloudSave();localSave()}
async function cloudSave(){const {error}=await supabase.from("budget_data").upsert({user_id:session.user.id,data:state,updated_at:new Date().toISOString()});if(error)console.error("Cloud save",error);localSave()}

function updateCardPreview(){const c=detectCard($("aInstitution").value,$("aName").value,$("aCardType").value),box=$("cardPreview");if(!c){box.classList.add("hidden");return}$("cardPreviewImg").src=cardPath(c);$("cardPreviewTitle").textContent=c.label;$("cardPreviewText").textContent="Imagen asignada automáticamente según el banco y tipo.";box.classList.remove("hidden")}

function renderProfile(){const p=state.profile||{}; $("pName").value=p.name||""; $("pPhone").value=p.phone||""; $("pCity").value=p.city||""; $("pNote").value=p.note||""; $("profileEmail").textContent=session?.user?.email||""; const img=$("profileImg"),top=$("topAvatar"); if(p.photo){img.src=p.photo;top.src=p.photo;img.classList.remove("hidden");top.classList.remove("hidden");}else{img.removeAttribute("src");top.removeAttribute("src");img.classList.remove("hidden");top.classList.remove("hidden");} $("topName").textContent=p.name||"Mi perfil";}
function render(){const t=totals();$("income").textContent=money(t.i);$("commitTotal").textContent=money(t.c);$("savingTotal").textContent=money(t.s);$("expenseTotal").textContent=money(t.e);$("available").textContent=money(t.a);$("incomePill").textContent="Ingresos "+money(t.i);$("savingPill").textContent="Ahorro "+money(t.s);const days=new Date(new Date().getFullYear(),new Date().getMonth()+1,0).getDate()-new Date().getDate()+1;$("dailySpend").textContent=`Límite orientativo: ${money(Math.max(0,t.a)/days)} por día hasta fin de mes.`;const used=Math.max(0,t.i-t.a),pct=Math.min(100,(used/Math.max(1,t.i))*100);$("usagePct").textContent=Math.round(pct)+"%";$("usageBar").style.width=pct+"%";$("traffic").textContent=t.a<0?"🔴 Presupuesto excedido. Conviene ajustar gastos.":pct>80?"🟡 Vas justo. Vigila los gastos variables.":"🟢 Buen control. Mantén el ritmo.";$("incomeInput").value=Number(state.income||0);$("savingGoal").value=t.s;$("savingGoalInput").value=t.s;$("goalText").textContent=money(t.s);$("goalBar").style.width=(t.s?Math.min(100,(t.s/Math.max(1,t.i))*100):0)+"%";$("goalMsg").textContent=t.s?`Tu meta representa ${Math.round(t.s/Math.max(1,t.i)*100)}% de tus ingresos.`:"Define una meta para comenzar.";$("savingProgress").textContent=money(t.s);const m=monthLabel(monthKey());$("monthLabel").textContent=m;renderChart(t);renderCommitments();renderExpenses();renderAccounts();renderProfile();renderIncomeUI();renderReports();}
function renderChart(t){const vals=[t.i,t.c,t.s,t.e,Math.max(0,t.a)],labels=["Ingreso","Comprom.","Ahorro","Gastos","Libre"],max=Math.max(...vals,1);$("chart").innerHTML=vals.map((v,i)=>`<div class="barbox"><div class="barvalue">${money(v).replace("RD$","")}</div><div class="bar" style="height:${Math.max(4,v/max*135)}px"></div><div class="barlabel">${labels[i]}</div></div>`).join("")}
function renderCommitments(){const dailyMode=state.incomeMode!=="monthly";$ ("commitments").innerHTML=state.commitments.map((x,i)=>{const paidNow=dailyMode&&isPaidThisMonth(x);return `<div class="item ${paidNow?"paid":""}"><div class="row"><div><strong>${esc(x.name)}</strong><br><span class="amount">${money(x.amount)}</span></div><div class="actions"><button class="btn ${paidNow?"light":"ok"}" data-pay="${i}">${paidNow?"Pagado":"Marcar pagado"}</button><button class="btn danger" data-delc="${i}">Eliminar</button></div></div></div>`}).join("")||'<p class="muted">No hay compromisos.</p>';document.querySelectorAll("[data-pay]").forEach(b=>b.onclick=async()=>{const x=state.commitments[+b.dataset.pay];x.paid=!x.paid;x.paidMonth=x.paid?monthKey():null;render();await cloudSave()});document.querySelectorAll("[data-delc]").forEach(b=>b.onclick=async()=>{state.commitments.splice(+b.dataset.delc,1);render();await cloudSave()})}
function renderExpenses(){const dailyMode=state.incomeMode!=="monthly";$ ("expenses").innerHTML=state.expenses.map((x,i)=>`<div class="item ${x.paid?"paid":""}"><div class="row"><div><strong>${esc(x.name)}</strong><br><span class="amount">${money(x.amount)}</span>${x.date?`<br><span class="muted" style="font-size:11px">${x.date}</span>`:""}</div><div class="actions">${dailyMode?`<button class="btn ${x.paid?"light":"ok"}" data-paye="${i}">${x.paid?"Pagado":"Marcar pagado"}</button>`:""}<button class="btn danger" data-dele="${i}">Eliminar</button></div></div></div>`).join("")||'<p class="muted">No hay gastos registrados.</p>';document.querySelectorAll("[data-paye]").forEach(b=>b.onclick=async()=>{const x=state.expenses[+b.dataset.paye];x.paid=!x.paid;x.paidMonth=x.paid?monthKey():null;render();await cloudSave()});document.querySelectorAll("[data-dele]").forEach(b=>b.onclick=async()=>{state.expenses.splice(+b.dataset.dele,1);render();await cloudSave()})}
function renderAccounts(){const make=(a)=>{const card=a.cardId?CARD_CATALOG.find(c=>c.id===a.cardId):detectCard(a.institution,a.name,a.cardType||"auto");const visual=card?`<div class="accountVisual"><img src="${cardPath(card)}" alt="${esc(card.label)}"></div>`:`<div class="accountIcon">${accountIcon(a.type)}</div>`;const label=card?card.label:(a.type==="paypal"?"PayPal":a.type==="bank"?"Cuenta bancaria":a.type==="cash"?"Efectivo":"Otra cuenta");return `<div class="item"><div class="account">${visual}<div class="accountMeta"><strong>${esc(a.name)}</strong><small>${esc(label)}</small></div><div style="text-align:right"><div class="amount">${money(a.balance)}</div><div class="actions" style="justify-content:flex-end;margin-top:5px"><button class="btn light" data-edita="${state.accounts.indexOf(a)}">Editar</button><button class="btn danger" data-dela="${state.accounts.indexOf(a)}">Eliminar</button></div></div></div></div>`};$("accountsList").innerHTML=state.accounts.map(make).join("")||'<p class="muted">Aún no has agregado cuentas.</p>';$('accountsPreview').innerHTML=state.accounts.slice(0,3).map(a=>{const card=a.cardId?CARD_CATALOG.find(c=>c.id===a.cardId):detectCard(a.institution,a.name,a.cardType||"auto");return `<div class="item"><div class="account">${card?`<div class="accountVisual"><img src="${cardPath(card)}" alt="${esc(card.label)}"></div>`:`<div class="accountIcon">${accountIcon(a.type)}</div>`}<div class="accountMeta"><strong>${esc(a.name)}</strong><small>${money(a.balance)}</small></div></div></div>`}).join("")||'<p class="muted">Agrega tu banco o PayPal.</p>';document.querySelectorAll("[data-edita]").forEach(b=>b.onclick=()=>openAccountForm(+b.dataset.edita));document.querySelectorAll("[data-dela]").forEach(b=>b.onclick=async()=>{state.accounts.splice(+b.dataset.dela,1);render();await cloudSave()})}
function tab(n){["dashboard","commitments","savings","expenses","accounts","profile","settings","reports"].forEach(x=>{const el=$(x+"Tab");if(!el)return;el.classList.toggle("hidden",x!==n);if(x===n){el.classList.remove("tab-section");void el.offsetWidth;el.classList.add("tab-section")}});document.querySelectorAll("nav button").forEach(b=>b.classList.toggle("active",b.dataset.tab===n));window.scrollTo({top:0,behavior:"smooth"})}
function renderIncomeUI(){document.querySelectorAll("[data-mode]").forEach(b=>b.classList.toggle("active",b.dataset.mode===state.incomeMode));const entry=state.incomeMode!=="monthly";$("monthlyIncomeBox").classList.toggle("hidden",entry);$("entryIncomeBox").classList.toggle("hidden",!entry);if(entry){$("incomeModeTitle").textContent=state.incomeMode==="daily"?"Ingresos diarios":"Ingresos quincenales";$("incomeMonthTotal").textContent=money(incomeForMonth(monthKey()));$("incomeDate").value=$("incomeDate").value||new Date().toISOString().slice(0,10);const k=monthKey();$("incomeEntries").innerHTML=state.incomeEntries.filter(x=>String(x.date||"").slice(0,7)===k).sort((a,b)=>String(b.date).localeCompare(String(a.date))).map((x,i)=>`<div class="item"><div class="row"><div><strong>${esc(x.concept||"Ingreso")}</strong><br><span class="muted" style="font-size:11px">${x.date}</span></div><div class="actions"><b class="positive">${money(x.amount)}</b><button class="btn danger" data-deli="${i}" data-id="${esc(x.id)}">Eliminar</button></div></div></div>`).join("")||'<p class="muted">Aún no hay ingresos registrados este mes.</p>';document.querySelectorAll("[data-deli]").forEach(b=>b.onclick=async()=>{state.incomeEntries=state.incomeEntries.filter(x=>x.id!==b.dataset.id);render();await cloudSave()})}}
function reportData(k){const h=state.monthHistory.find(x=>x.month===k);if(k===monthKey()){const t=totals();return{month:k,income:t.i,commit:t.c,saving:t.s,expense:t.e,available:t.a}}if(h)return h;return{month:k,income:0,commit:0,saving:0,expense:0,available:0}}
function renderReports(){if(!$('reportsTab'))return;const months=[...new Set([monthKey(),...state.monthHistory.map(x=>x.month)])].sort().reverse();$('reportMonth').innerHTML=months.map(k=>`<option value="${k}">${monthLabel(k)}</option>`).join("");if(!months.includes($('reportMonth').value))$('reportMonth').value=monthKey();const d=reportData($('reportMonth').value);$('rIncome').textContent=money(d.income);$('rCommit').textContent=money(d.commit);$('rSaving').textContent=money(d.saving);$('rAvailable').textContent=money(d.available);$('rHealth').textContent=d.available<0?'🔴 Excedido':d.available===0?'🟡 Sin margen':'🟢 Positivo';const vals=[d.income,d.commit,d.saving,d.expense,Math.max(0,d.available)],labels=['Ingreso','Comprom.','Ahorro','Gastos','Libre'],max=Math.max(...vals,1);$('reportBars').innerHTML=vals.map((v,i)=>`<div class="barbox"><div class="barvalue">${money(v).replace('RD$','')}</div><div class="bar" style="height:${Math.max(4,v/max*135)}px"></div><div class="barlabel">${labels[i]}</div></div>`).join("");const older=months.filter(x=>x<d.month).sort().pop();const prev=older?reportData(older):null;$('reportComparison').innerHTML=prev?`<div class="item"><div class="row"><span>Mes anterior</span><b>${monthLabel(prev.month)}</b></div><div class="row" style="margin-top:8px"><span>Ingresos</span><b>${pctChange(d.income,prev.income)}</b></div><div class="row" style="margin-top:6px"><span>Disponible</span><b>${pctChange(d.available,prev.available)}</b></div><div class="row" style="margin-top:6px"><span>Ahorro</span><b>${pctChange(d.saving,prev.saving)}</b></div></div>`:'<p class="muted">Guarda tu primer cierre mensual para empezar a comparar.</p>';$('historyTable').innerHTML=state.monthHistory.slice().sort((a,b)=>b.month.localeCompare(a.month)).map(h=>`<div class="item"><div class="row"><strong>${monthLabel(h.month)}</strong><b>${money(h.income)}</b></div><div class="muted" style="font-size:11px;margin-top:5px">Gastos: ${money(h.expense)} · Ahorro: ${money(h.saving)} · Disponible: ${money(h.available)}</div></div>`).join("")||'<p class="muted">Todavía no hay cierres guardados.</p>'}
function pctChange(a,b){if(!Number(b))return '—';const p=((Number(a)-Number(b))/Math.abs(Number(b)))*100;return (p>=0?'+':'')+p.toFixed(1)+'%'}
function isRecoveryFlow(){return location.search.includes("reset=1")||location.hash.includes("type=recovery")||location.hash.includes("access_token=")&&location.hash.includes("type=recovery")}
async function refresh(s){session=s;const recovery=isRecoveryFlow();if(s && !recovery){localLoad();await cloudLoad();$("authView").classList.add("hidden");$("appView").classList.remove("hidden");$("nav").classList.remove("hidden");$("appHeader").classList.remove("hidden");render();tab("dashboard")}else{$("authView").classList.remove("hidden");$("appView").classList.add("hidden");$("nav").classList.add("hidden");$("appHeader").classList.add("hidden");authPanel(recovery?"resetPanel":"welcomePanel")}}
function authPanel(name){["welcomePanel","loginPanel","signupPanel","forgotPanel","resetPanel"].forEach(id=>$(id).classList.toggle("hidden",id!==name));["authMsg","signupMsg","forgotMsg","resetMsg"].forEach(id=>{if($(id))$(id).classList.add("hidden")})}
function showMsg(id,t,error=false){const el=$(id);el.textContent=t;el.classList.remove("hidden");el.classList.toggle("error",error)}
$("goLogin").onclick=()=>authPanel("loginPanel");$("goSignup").onclick=()=>authPanel("signupPanel");$("goSignup2").onclick=()=>authPanel("signupPanel");$("goLogin2").onclick=()=>authPanel("loginPanel");$("forgotBtn").onclick=()=>{$("forgotEmail").value=$("email").value.trim();authPanel("forgotPanel")};$("backLogin").onclick=()=>authPanel("loginPanel");
$("loginBtn").onclick=async()=>{showMsg("authMsg","",false);$("authMsg").classList.add("hidden");const email=$("email").value.trim(),password=$("password").value;if(!email||!password)return showMsg("authMsg","Escribe tu correo y contraseña.",true);const {data,error}=await supabase.auth.signInWithPassword({email,password});if(error)showMsg("authMsg","No se pudo iniciar sesión. Revisa el correo y la contraseña.",true);else await refresh(data.session)};
$("signupBtn").onclick=async()=>{showMsg("signupMsg","",false);$("signupMsg").classList.add("hidden");const email=$("signupEmail").value.trim(),password=$("signupPassword").value,password2=$("signupPassword2").value;if(!email||password.length<6)return showMsg("signupMsg","Usa un correo válido y una contraseña de al menos 6 caracteres.",true);if(password!==password2)return showMsg("signupMsg","Las contraseñas no coinciden.",true);const {data,error}=await supabase.auth.signUp({email,password,options:{emailRedirectTo:APP_URL}});if(error)return showMsg("signupMsg","No se pudo crear la cuenta: "+error.message,true);if(data.session)await refresh(data.session);else showMsg("signupMsg","Cuenta creada. Revisa tu correo para confirmar la cuenta y luego inicia sesión.")};
$("sendReset").onclick=async()=>{const email=$("forgotEmail").value.trim();if(!email)return showMsg("forgotMsg","Escribe tu correo electrónico.",true);const {error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:RECOVERY_REDIRECT});if(error)showMsg("forgotMsg","No se pudo enviar el enlace: "+(error.message||"error desconocido"),true);else showMsg("forgotMsg","Enlace enviado. Revisa tu correo y también la carpeta de spam.")};
$("updatePassword").onclick=async()=>{const p=$("newPassword").value,p2=$("newPassword2").value;if(p.length<6)return showMsg("resetMsg","La contraseña debe tener al menos 6 caracteres.",true);if(p!==p2)return showMsg("resetMsg","Las contraseñas no coinciden.",true);const {error}=await supabase.auth.updateUser({password:p});if(error)showMsg("resetMsg","No se pudo actualizar la contraseña. Es posible que el enlace haya expirado; solicita uno nuevo.",true);else{showMsg("resetMsg","Contraseña actualizada correctamente. Ahora inicia sesión con tu nueva contraseña.");setTimeout(async()=>{history.replaceState({},document.title,APP_URL);await supabase.auth.signOut();session=null;authPanel("loginPanel")},900)}};
$("logoutBtn").onclick=async()=>{await supabase.auth.signOut();location.reload()};$("addCommit").onclick=async()=>{const n=$("cName").value.trim(),a=Number($("cAmount").value);if(!n||a<=0)return;state.commitments.push({name:n,amount:a,paid:false});$("cName").value="";$("cAmount").value="";render();await cloudSave()};$("addExpense").onclick=async()=>{const n=$("eName").value.trim(),a=Number($("eAmount").value);if(!n||a<=0)return;state.expenses.push({name:n,amount:a,date:new Date().toISOString().slice(0,10)});$("eName").value="";$("eAmount").value="";render();await cloudSave()};$("saveGoal").onclick=async()=>{state.savingGoal=Math.max(0,Number($("savingGoal").value));render();await cloudSave()};document.querySelectorAll("[data-mode]").forEach(b=>b.onclick=async()=>{state.incomeMode=b.dataset.mode;render();await cloudSave()});$("addIncomeEntry").onclick=async()=>{const amount=Number($("incomeAmount").value),date=$("incomeDate").value||new Date().toISOString().slice(0,10),concept=$("incomeConcept").value.trim()||"Ingreso";if(amount<=0)return;state.incomeEntries.push({id:crypto.randomUUID(),amount,date,concept,mode:state.incomeMode});$("incomeAmount").value="";$("incomeConcept").value="";render();await cloudSave()};$("saveSettings").onclick=async()=>{state.income=Math.max(0,Number($("incomeInput").value)||0);state.savingGoal=Math.max(0,Number($("savingGoalInput").value)||0);render();showMsg("settingsMsg","Cambios guardados correctamente.");await cloudSave()};$("closeMonth").onclick=async()=>{const k=monthKey(),t=totals(),i=state.monthHistory.findIndex(h=>h.month===k),snap={month:k,income:t.i,commit:t.c,saving:t.s,expense:t.e,available:t.a,closedAt:new Date().toISOString()};if(i>=0)state.monthHistory[i]=snap;else state.monthHistory.push(snap);render();showMsg("settingsMsg","Cierre del mes guardado en Reportes.");await cloudSave()};$("reportMonth").onchange=()=>renderReports();
document.querySelectorAll("nav button,[data-tab]").forEach(b=>b.onclick=()=>tab(b.dataset.tab));
let editingAccountIndex=-1;
function resetAccountForm(){editingAccountIndex=-1;$('accountFormTitle').textContent='Nueva cuenta';$('aType').value='bank';$('aName').value='';$('aInstitution').value='';$('aCardType').value='auto';$('aBalance').value='';$('cardPreview').classList.add('hidden')}
function openAccountForm(i=-1){editingAccountIndex=i;if(i>=0){const a=state.accounts[i]||{};$('accountFormTitle').textContent='Editar cuenta';$('aType').value=a.type||'bank';$('aName').value=a.name||'';$('aInstitution').value=a.institution||'';$('aCardType').value=a.cardType||'auto';$('aBalance').value=Number(a.balance||0);updateCardPreview()}else{resetAccountForm();updateCardPreview()}$('accountForm').classList.remove('hidden')}
$('profileQuick').onclick=()=>tab('profile');$('addAccountBtn').onclick=()=>openAccountForm();$('cancelAccount').onclick=()=>{$('accountForm').classList.add('hidden');resetAccountForm()};$('aType').onchange=()=>{if($('aType').value==='paypal'){$('aInstitution').value='PayPal';$('aCardType').value='auto'}updateCardPreview()};$('aInstitution').oninput=updateCardPreview;$('aName').oninput=updateCardPreview;$('aCardType').onchange=updateCardPreview;
$('saveAccount').onclick=async()=>{const n=$('aName').value.trim(),bal=Number($('aBalance').value),type=$('aType').value,institution=$('aInstitution').value.trim(),cardType=$('aCardType').value,card=detectCard(institution,n,cardType);if(!n)return;if(editingAccountIndex>=0){const current=state.accounts[editingAccountIndex]||{};state.accounts[editingAccountIndex]={...current,type,name:n,balance:bal||0,institution,cardType,cardId:card?.id||null}}else{state.accounts.push({type,name:n,balance:bal||0,institution,cardType,cardId:card?.id||null})}$('accountForm').classList.add('hidden');resetAccountForm();render();await cloudSave()};
$("saveProfile").onclick=async()=>{state.profile={...state.profile,name:$("pName").value.trim(),phone:$("pPhone").value.trim(),city:$("pCity").value.trim(),note:$("pNote").value.trim()};localSave();render();await cloudSave();showMsg("authMsg","",false);alert("Perfil guardado correctamente.")};$("photoInput").onchange=e=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{const im=new Image();im.onload=()=>{const c=document.createElement("canvas"),max=420,scale=Math.min(1,max/Math.max(im.width,im.height));c.width=Math.round(im.width*scale);c.height=Math.round(im.height*scale);c.getContext("2d").drawImage(im,0,0,c.width,c.height);state.profile.photo=c.toDataURL("image/jpeg",.78);render();cloudSave()};im.src=r.result};r.readAsDataURL(f)};
supabase.auth.onAuthStateChange((event,s)=>{if(event==="PASSWORD_RECOVERY"){session=s;authPanel("resetPanel");$("appHeader").classList.add("hidden");$("nav").classList.add("hidden");$("appView").classList.add("hidden");$("authView").classList.remove("hidden")}setTimeout(()=>refresh(s),0)});document.querySelectorAll('#email,#password').forEach(el=>el.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();$('loginBtn').click()}}));
const {data:{session:s0}}=await supabase.auth.getSession();
if(isRecoveryFlow()){$('appHeader').classList.add('hidden');$('nav').classList.add('hidden');$('appView').classList.add('hidden');$('authView').classList.remove('hidden');authPanel('resetPanel')}else{if(s0)await supabase.auth.signOut({scope:'local'});session=null;await refresh(null)}
