import { supabase, APP_URL, RECOVERY_REDIRECT } from "../services/supabase.js";
import { $ , showMsg } from "../ui/dom.js";
import { tab, authPanel } from "../ui/navigation.js";
import { renderDashboard } from "../ui/renderDashboard.js";
import { renderCommitments, renderExpenses, renderIncomeUI, renderReports } from "../ui/renderBudget.js";
import { CARD_CATALOG, detectCard, cardPath } from "../services/cards.js";
import { createInitialState, normalizeState, loadLocalState, saveLocalState } from "../core/state.js";
import { money, esc, monthKey, monthLabel, incomeForMonth, isPaidThisMonth, totals } from "../core/calculations.js";
import { accountIcon } from "../core/accounts.js";
import { addIncomeEntry, removeIncomeEntry } from "../core/income.js";
import { addCommitment, toggleCommitmentPaid, removeCommitment } from "../core/commitments.js";
import { addExpense, toggleExpensePaid, removeExpense } from "../core/expenses.js";
import { setSavingGoal } from "../core/savings.js";
import { reportData, closeCurrentMonth, pctChange } from "../core/reports.js";

let state=createInitialState(),session=null;

function localSave(){saveLocalState(session?.user?.id,state)}
function localLoad(){const x=loadLocalState(session?.user?.id);if(x)state=x}
async function cloudLoad(){const {data,error}=await supabase.from("budget_data").select("data").eq("user_id",session.user.id).maybeSingle();if(error){console.error(error);return}if(data?.data)state=normalizeState(data.data);else await cloudSave();localSave()}
async function cloudSave(){const {error}=await supabase.from("budget_data").upsert({user_id:session.user.id,data:state,updated_at:new Date().toISOString()});if(error)console.error("Cloud save",error);localSave()}

function updateCardPreview(){const c=detectCard($("aInstitution").value,$("aName").value,$("aCardType").value),box=$("cardPreview");if(!c){box.classList.add("hidden");return}$("cardPreviewImg").src=cardPath(c);$("cardPreviewTitle").textContent=c.label;$("cardPreviewText").textContent="Imagen asignada automáticamente según el banco y tipo.";box.classList.remove("hidden")}

function renderProfile(){const p=state.profile||{}; $("pName").value=p.name||""; $("pPhone").value=p.phone||""; $("pCity").value=p.city||""; $("pNote").value=p.note||""; $("profileEmail").textContent=session?.user?.email||""; const img=$("profileImg"),top=$("topAvatar"); if(p.photo){img.src=p.photo;top.src=p.photo;img.classList.remove("hidden");top.classList.remove("hidden");}else{img.removeAttribute("src");top.removeAttribute("src");img.classList.remove("hidden");top.classList.remove("hidden");} $("topName").textContent=p.name||"Mi perfil";}
function render(){renderDashboard(state);renderCommitments(state,render,cloudSave);renderExpenses(state,render,cloudSave);renderAccounts();renderProfile();renderIncomeUI(state,render,cloudSave);renderReports(state);}
function renderAccounts(){const make=(a)=>{const card=a.cardId?CARD_CATALOG.find(c=>c.id===a.cardId):detectCard(a.institution,a.name,a.cardType||"auto");const visual=card?`<div class="accountVisual"><img src="${cardPath(card)}" alt="${esc(card.label)}"></div>`:`<div class="accountIcon">${accountIcon(a.type)}</div>`;const label=card?card.label:(a.type==="paypal"?"PayPal":a.type==="bank"?"Cuenta bancaria":a.type==="cash"?"Efectivo":"Otra cuenta");return `<div class="item"><div class="account">${visual}<div class="accountMeta"><strong>${esc(a.name)}</strong><small>${esc(label)}</small></div><div style="text-align:right"><div class="amount">${money(a.balance)}</div><div class="actions" style="justify-content:flex-end;margin-top:5px"><button class="btn light" data-edita="${state.accounts.indexOf(a)}">Editar</button><button class="btn danger" data-dela="${state.accounts.indexOf(a)}">Eliminar</button></div></div></div></div>`};$("accountsList").innerHTML=state.accounts.map(make).join("")||'<p class="muted">Aún no has agregado cuentas.</p>';$('accountsPreview').innerHTML=state.accounts.slice(0,3).map(a=>{const card=a.cardId?CARD_CATALOG.find(c=>c.id===a.cardId):detectCard(a.institution,a.name,a.cardType||"auto");return `<div class="item"><div class="account">${card?`<div class="accountVisual"><img src="${cardPath(card)}" alt="${esc(card.label)}"></div>`:`<div class="accountIcon">${accountIcon(a.type)}</div>`}<div class="accountMeta"><strong>${esc(a.name)}</strong><small>${money(a.balance)}</small></div></div></div>`}).join("")||'<p class="muted">Agrega tu banco o PayPal.</p>';document.querySelectorAll("[data-edita]").forEach(b=>b.onclick=()=>openAccountForm(+b.dataset.edita));document.querySelectorAll("[data-dela]").forEach(b=>b.onclick=async()=>{state.accounts.splice(+b.dataset.dela,1);render();await cloudSave()})}
function isRecoveryFlow(){return location.search.includes("reset=1")||location.hash.includes("type=recovery")||location.hash.includes("access_token=")&&location.hash.includes("type=recovery")}
async function refresh(s){session=s;const recovery=isRecoveryFlow();if(s && !recovery){localLoad();await cloudLoad();$("authView").classList.add("hidden");$("appView").classList.remove("hidden");$("nav").classList.remove("hidden");$("appHeader").classList.remove("hidden");render();tab("dashboard")}else{$("authView").classList.remove("hidden");$("appView").classList.add("hidden");$("nav").classList.add("hidden");$("appHeader").classList.add("hidden");authPanel(recovery?"resetPanel":"welcomePanel")}}
$("goLogin").onclick=()=>authPanel("loginPanel");$("goSignup").onclick=()=>authPanel("signupPanel");$("goSignup2").onclick=()=>authPanel("signupPanel");$("goLogin2").onclick=()=>authPanel("loginPanel");$("forgotBtn").onclick=()=>{$("forgotEmail").value=$("email").value.trim();authPanel("forgotPanel")};$("backLogin").onclick=()=>authPanel("loginPanel");
$("loginBtn").onclick=async()=>{showMsg("authMsg","",false);$("authMsg").classList.add("hidden");const email=$("email").value.trim(),password=$("password").value;if(!email||!password)return showMsg("authMsg","Escribe tu correo y contraseña.",true);const {data,error}=await supabase.auth.signInWithPassword({email,password});if(error)showMsg("authMsg","No se pudo iniciar sesión. Revisa el correo y la contraseña.",true);else await refresh(data.session)};
$("signupBtn").onclick=async()=>{showMsg("signupMsg","",false);$("signupMsg").classList.add("hidden");const email=$("signupEmail").value.trim(),password=$("signupPassword").value,password2=$("signupPassword2").value;if(!email||password.length<6)return showMsg("signupMsg","Usa un correo válido y una contraseña de al menos 6 caracteres.",true);if(password!==password2)return showMsg("signupMsg","Las contraseñas no coinciden.",true);const {data,error}=await supabase.auth.signUp({email,password,options:{emailRedirectTo:APP_URL}});if(error)return showMsg("signupMsg","No se pudo crear la cuenta: "+error.message,true);if(data.session)await refresh(data.session);else showMsg("signupMsg","Cuenta creada. Revisa tu correo para confirmar la cuenta y luego inicia sesión.")};
$("sendReset").onclick=async()=>{const email=$("forgotEmail").value.trim();if(!email)return showMsg("forgotMsg","Escribe tu correo electrónico.",true);const {error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:RECOVERY_REDIRECT});if(error)showMsg("forgotMsg","No se pudo enviar el enlace: "+(error.message||"error desconocido"),true);else showMsg("forgotMsg","Enlace enviado. Revisa tu correo y también la carpeta de spam.")};
$("updatePassword").onclick=async()=>{const p=$("newPassword").value,p2=$("newPassword2").value;if(p.length<6)return showMsg("resetMsg","La contraseña debe tener al menos 6 caracteres.",true);if(p!==p2)return showMsg("resetMsg","Las contraseñas no coinciden.",true);const {error}=await supabase.auth.updateUser({password:p});if(error)showMsg("resetMsg","No se pudo actualizar la contraseña. Es posible que el enlace haya expirado; solicita uno nuevo.",true);else{showMsg("resetMsg","Contraseña actualizada correctamente. Ahora inicia sesión con tu nueva contraseña.");setTimeout(async()=>{history.replaceState({},document.title,APP_URL);await supabase.auth.signOut();session=null;authPanel("loginPanel")},900)}};
$("logoutBtn").onclick=async()=>{await supabase.auth.signOut();location.reload()};$("addCommit").onclick=async()=>{const n=$("cName").value.trim(),a=Number($("cAmount").value);if(!n||a<=0)return;addCommitment(state,n,a);$("cName").value="";$("cAmount").value="";render();await cloudSave()};$("addExpense").onclick=async()=>{const n=$("eName").value.trim(),a=Number($("eAmount").value);if(!n||a<=0)return;addExpense(state,n,a);$("eName").value="";$("eAmount").value="";render();await cloudSave()};$("saveGoal").onclick=async()=>{setSavingGoal(state,$("savingGoal").value);render();await cloudSave()};document.querySelectorAll("[data-mode]").forEach(b=>b.onclick=async()=>{state.incomeMode=b.dataset.mode;render();await cloudSave()});$("addIncomeEntry").onclick=async()=>{const amount=Number($("incomeAmount").value),date=$("incomeDate").value||new Date().toISOString().slice(0,10),concept=$("incomeConcept").value.trim()||"Ingreso";if(amount<=0)return;addIncomeEntry(state,{amount,date,concept,mode:state.incomeMode});$("incomeAmount").value="";$("incomeConcept").value="";render();await cloudSave()};$("saveSettings").onclick=async()=>{state.income=Math.max(0,Number($("incomeInput").value)||0);setSavingGoal(state,$("savingGoalInput").value);render();showMsg("settingsMsg","Cambios guardados correctamente.");await cloudSave()};$("closeMonth").onclick=async()=>{closeCurrentMonth(state);render();showMsg("settingsMsg","Cierre del mes guardado en Reportes.");await cloudSave()};$("reportMonth").onchange=()=>renderReports();
document.querySelectorAll("nav button,[data-tab]").forEach(b=>b.onclick=()=>tab(b.dataset.tab));
let editingAccountIndex=-1;
function resetAccountForm(){editingAccountIndex=-1;$('accountFormTitle').textContent='Nueva cuenta';$('aType').value='bank';$('aName').value='';$('aInstitution').value='';$('aCardType').value='auto';$('aBalance').value='';$('cardPreview').classList.add('hidden')}
function openAccountForm(i=-1){editingAccountIndex=i;if(i>=0){const a=state.accounts[i]||{};$('accountFormTitle').textContent='Editar cuenta';$('aType').value=a.type||'bank';$('aName').value=a.name||'';$('aInstitution').value=a.institution||'';$('aCardType').value=a.cardType||'auto';$('aBalance').value=Number(a.balance||0);updateCardPreview()}else{resetAccountForm();updateCardPreview()}$('accountForm').classList.remove('hidden')}
$('profileQuick').onclick=()=>tab('profile');$('addAccountBtn').onclick=()=>openAccountForm();$('cancelAccount').onclick=()=>{$('accountForm').classList.add('hidden');resetAccountForm()};$('aType').onchange=()=>{if($('aType').value==='paypal'){$('aInstitution').value='PayPal';$('aCardType').value='auto'}updateCardPreview()};$('aInstitution').oninput=updateCardPreview;$('aName').oninput=updateCardPreview;$('aCardType').onchange=updateCardPreview;
$('saveAccount').onclick=async()=>{const n=$('aName').value.trim(),bal=Number($('aBalance').value),type=$('aType').value,institution=$('aInstitution').value.trim(),cardType=$('aCardType').value,card=detectCard(institution,n,cardType);if(!n)return;if(editingAccountIndex>=0){const current=state.accounts[editingAccountIndex]||{};state.accounts[editingAccountIndex]={...current,type,name:n,balance:bal||0,institution,cardType,cardId:card?.id||null}}else{state.accounts.push({type,name:n,balance:bal||0,institution,cardType,cardId:card?.id||null})}$('accountForm').classList.add('hidden');resetAccountForm();render();await cloudSave()};
$("saveProfile").onclick=async()=>{state.profile={...state.profile,name:$("pName").value.trim(),phone:$("pPhone").value.trim(),city:$("pCity").value.trim(),note:$("pNote").value.trim()};localSave();render();await cloudSave();showMsg("authMsg","",false);alert("Perfil guardado correctamente.")};$("photoInput").onchange=e=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{const im=new Image();im.onload=()=>{const c=document.createElement("canvas"),max=420,scale=Math.min(1,max/Math.max(im.width,im.height));c.width=Math.round(im.width*scale);c.height=Math.round(im.height*scale);c.getContext("2d").drawImage(im,0,0,c.width,c.height);state.profile.photo=c.toDataURL("image/jpeg",.78);render();cloudSave()};im.src=r.result};r.readAsDataURL(f)};
supabase.auth.onAuthStateChange((event,s)=>{if(event==="PASSWORD_RECOVERY"){session=s;authPanel("resetPanel");$("appHeader").classList.add("hidden");$("nav").classList.add("hidden");$("appView").classList.add("hidden");$("authView").classList.remove("hidden")}setTimeout(()=>refresh(s),0)});document.querySelectorAll('#email,#password').forEach(el=>el.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();$('loginBtn').click()}}));
const {data:{session:s0}}=await supabase.auth.getSession();
if(isRecoveryFlow()){$('appHeader').classList.add('hidden');$('nav').classList.add('hidden');$('appView').classList.add('hidden');$('authView').classList.remove('hidden');authPanel('resetPanel')}else{if(s0)await supabase.auth.signOut({scope:'local'});session=null;await refresh(null)}
